name: Github Trend Daily

on:
  schedule:
    # - cron: "0 0 * * *" # Run every day at midnight UTC
    - cron: '0 15 * * *' 
  workflow_dispatch: {}

jobs:
  generate-and-upload:
    name: Generate and upload trend data to kaggle
    runs-on: ubuntu-latest

    steps:
      - name: 0. Print current date and time
        run: echo "The current date and time is $(date)"

      - name: 1. 📍Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: 2. 📦Install ghtrend package and Kaggle cli
        run: pip install ghtrend kaggle

      - name: 3. 🪄Generate daily CSV report
        run: |
          mkdir $(date '+%Y%m%d')
          ghtrend daily $(date '+%Y%m%d')/$(date '+%Y%m%d').csv
        
      - name: 4. 🔑Authenticate with Kaggle API
        run: |
          mkdir -p ~/.kaggle
          echo '{"username":"${{ secrets.KAGGLE_USERNAME }}","key":"${{ secrets.KAGGLE_API_TOKEN }}"}' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: 5. ☁️Upload CSV to Kaggle
        run: kaggle datasets version -p $(date '+%Y%m%d') -m "$(date '+%Y%m%d') daily github trend uploaded."
